// <auto-generated />
using Mall.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mall.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201203011622_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mall.Models.CuentasBancarias", b =>
                {
                    b.Property<int>("CuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<int>("JugadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numeracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTarjeta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("CuentaId");

                    b.ToTable("CuentasBancarias");
                });

            modelBuilder.Entity("Mall.Models.Jugadores", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archivo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Dinero")
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores");

                    b.HasData(
                        new
                        {
                            JugadorId = 1,
                            Archivo = 0,
                            Dinero = 0m,
                            Edad = 0,
                            Nombres = ""
                        },
                        new
                        {
                            JugadorId = 2,
                            Archivo = 0,
                            Dinero = 0m,
                            Edad = 0,
                            Nombres = ""
                        },
                        new
                        {
                            JugadorId = 3,
                            Archivo = 0,
                            Dinero = 0m,
                            Edad = 0,
                            Nombres = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
